# Site settings
title: "William Linker"
#description: "A resume."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "William Linker"
resume_title:                   "Student &mdash; Writer &mdash; Maker"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "w.a.linker@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
#resume_contact_telephone:       " "
#resume_contact_address:         " "

resume_header_contact_info:     ""
display_header_contact_info:    "false"

resume_header_intro: "<p>Hello! I'm Will Linker, an experienced office administration and customer service professional.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        ""

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
# resume_section_projects:        true
resume_section_skills:          true
# resume_section_recognition:     true
resume_section_links:           true
# resume_section_associations:    true
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/wlinker1"
  resume_twitter_url:           "http://twitter.com/WilliamLinker"
  resume_linkedin_url:          "https://www.linkedin.com/in/william-linker"
  resume_website_url:           "http://williamlinker.com"
resume_print_social_links:      true

# Design settings
resume_theme:                   default
